### ISSUE TITLE
Feature Suggestion: Private Roll Color adjustment

### ISSUE THREAD

**Issue by JacobMcAuley** [iotech-fvtt/fantasy-ui#1]
Currently, the private/blind roll has no way to differentiate itself from a roll of a non-hidden variety.

The attached image below shows the issue. The top roll is a public roll and the bottom roll is the private roll; however, it's not possible to tell by looking.

![image](https://user-images.githubusercontent.com/12160735/83995560-96088b00-a90e-11ea-8830-69f7d0aea09d.png)

**Comment by iotech-fvtt** [comment]
Within the boundaries of what I can do with CSS, what would you like to see? Different color? Italic? Give me some suggestions :)

**Comment by iotech-fvtt** [comment]
Pushed to production in 0.1.13
