### ISSUE TITLE
Effects icon disappears on Pathfinder 2e system

### ISSUE THREAD

**Issue by Tarmorax** [iotech-fvtt/fantasy-ui#11]
Hello. I love this UI, thank you for your work on it. However, in the Pathfinder 2e system it breaks the effect icon that appears in the upper-right when I activate this module. As soon as I activate Fantasy UI, the effect disappears and reappears when I disable the module.

I'm using the following versions:
fantasy UI : 0.1.21
Foundry :0.8.9
Pathfinder 2e: 2.13.3.7822

![Ticket03](https://user-images.githubusercontent.com/3279088/132278554-532f289e-6676-4f6e-89cd-f39d69fdb622.png)

**Comment by Tarmorax** [comment]
Here's what it looks like with Fantasy UI activated: 
![image](https://user-images.githubusercontent.com/3279088/132278646-9fb6f767-1b5f-4631-8154-385a7ef1f0cd.png)

**Comment by iotech-fvtt** [comment]
Is that Effects icon baked into the PF2E system, or is it a module? If so, which?

**Comment by Tarmorax** [comment]
it's baked into the PF2e system. In that system they have spell effects and it automatically calculates when they expire. Thanks for the quick answer.

**Comment by iotech-fvtt** [comment]
Ok, I'll check it out tonight when I get home from work.

**Comment by iotech-fvtt** [comment]
It seems the sidebar I made in FantasyUI is wider than the standard sidebar, and the author of PF2E chose to hard code the Effect icons location on the screen. The wider Fantasy-UI sidebar is covering the baked-in Effect icons. 

Easy fix that doesnt require anyone to change any code:
1. If you have not already, install the module Custom CSS
2. In the Configure Settings, Module Settings tab, click the button under Custom CSS to open the custom css editor.
3. Paste this in there: 
.effect-panel {
right: 375px !important;
}

4. Save and close all open windows.
5. Profit ;)
![chrome_7SnlpufVKQ](https://user-images.githubusercontent.com/29070865/132417309-2ace0775-bc72-404f-be9f-4f5a1109d977.png)
