### ISSUE TITLE
Ui doesn't fit with V9 of foundry because of Card icon

### ISSUE THREAD

**Issue by Tarmorax** [iotech-fvtt/fantasy-ui#12]
Since V9 of Foundry added a card icon, the current iteration of Fantasy-UI doesn't have an icon for cards. Also, since it squished all the other icons, the other icons get cut-off.

I don't know if this UI is still supported but if so thank you in advance for your time. I've been using for about a year and it's great. 

![FantasyUIv9](https://user-images.githubusercontent.com/3279088/148160880-3ade6de0-07d2-466c-81e5-b114dc00e6e3.png)

**Comment by iotech-fvtt** [comment]
I just finally switched to v9 a couple of days ago, and yeah... FantasyUi is broken. I will probably fix it eventually, but as I dont use it anymore myself, it's a lower priority. I *do* have a new UI based on Fantasy UI that I've updated but not released. Many of the same icons, but bigger (I am developing vision problems). I'd be happy to give you a copy (can't attach here, email me at gerry (at) e911systems.com)).
![chrome_LzxVBfOelA](https://user-images.githubusercontent.com/29070865/148161999-a7452d9b-2b3d-44f9-a8de-c9af38080cd7.png)

**Comment by Medik-GH** [comment]
I hope you don't mind but I forked your UI and fixed it up for V9 and added some other changes. Just dropping it here incase it might be useful for anyone else.. keep up the great work.

https://github.com/EddieEldridge/medik-foundry-ui

**Comment by iotech-fvtt** [comment]
I dont mind at all! I've been working on an overhaul (see my screenshot above for an example) with larger icons. I realize this may not be to everyone's taste. Anyway, you can do whatever you like with it. Also appreciate you sharing a fixed version on the small-icon style!

**Comment by Nostalgia2046** [comment]
> I hope you don't mind but I forked your UI and fixed it up for V9 and added some other changes. Just dropping it here incase it might be useful for anyone else.. keep up the great work.
> 
> https://github.com/EddieEldridge/medik-foundry-ui

Thanks for posting this fix ! I wish you would keep the same "scene" icon but hey still a super cool job. And thanks Iotech for this amazing ui, definetely my all time favourite with a real fantasy feel.

**Comment by iotech-fvtt** [comment]
v9 compatible release coming in the next few days. This repository is updated, you can pull it now, just havent done the release package or the Foundry installer stuff yet.

**Comment by iotech-fvtt** [comment]
Files in repo updated BUT no manifest yet, so if you do install this right now, it will never update. Will finish this release in the next few days.

**Comment by iotech-fvtt** [comment]
Release 0.2.0:
https://raw.githubusercontent.com/iotech-fvtt/fantasy-ui/master/module.json

**Comment by iotech-fvtt** [comment]
"beta" of v3, in case you want to loo
[fantasy-ui-3.zip](https://github.com/iotech-fvtt/fantasy-ui/files/8310373/fantasy-ui-3.zip)
k
