### ISSUE TITLE
Different sizes for the UI (Suggestion)

### ISSUE THREAD

**Issue by Darkiller25** [iotech-fvtt/fantasy-ui#13]
Hi! First of all, I love the new design! With that said, the buttons used to be BIG, but now they seem to be way smaller than normal it makes it hard to read at a glance. 

Would it be possible to have different UI sizes?

**Comment by iotech-fvtt** [comment]
Which buttons do you mean? The tabs (Scenes, Journal, etc.) or the green buttons found ON each tab?

**Comment by Darkiller25** [comment]
Hi! The text and buttons on the tabs (like actors and scenes) are way smaller than they used to be. A little too much for MY personal tastes, but if it was possible to resize them... that'd be great!

![New_UI](https://user-images.githubusercontent.com/71094682/157370794-a8343468-92e8-471b-9848-de872d80ec70.png)

**Comment by iotech-fvtt** [comment]
Ah, I see. That's Plutonium doing that. It has a setting for "compact"
lists or something.

**Comment by Darkiller25** [comment]
OMG I'll try changing this right away! Thanks :)

Well, it didn't change anything :/ I unchecked all "compact" things in the UI settings.

I also checked with Find The Culprit and just FantasyUI enabled, and it ends up the same. 

*Update* So by disabling the compact options from Plutonium, it does make the scenes and actors bigger, but the folders are still way smaller than in the past version.

**Comment by Darkiller25** [comment]
This is with everything compact being disabled
![New_UI2](https://user-images.githubusercontent.com/71094682/157503062-3efe0589-b43d-476c-baab-7d6f799c6d9c.png)

**Comment by iotech-fvtt** [comment]
Hmm ok, I'll take another look after work.

**Comment by Darkiller25** [comment]
Sure, thank you! (by the way, are they supposed to be that small? maybe it's just the way it is now)

**Comment by iotech-fvtt** [comment]
I may have made them smaller. Most users prefer the smaller size. I do
personally too, but I can probably make it a bit bigger. Or make you a
standalone version with original default size.

**Comment by Darkiller25** [comment]
Hmm it's true that the original module was WAY bigger :P but an in-between would be great :)

**Comment by Darkiller25** [comment]
is it something I could easily modify myself?

**Comment by iotech-fvtt** [comment]
If you know CSS, yes, with the CustomCSS module.

**Comment by Darkiller25** [comment]
I do not... but would that be a lot of work just for this? I don't want to make you work a lot just for this :P

**Comment by iotech-fvtt** [comment]
Ok, take the attached file and overwrite the one in your /modules/fantasyui, then refresh your browser. Let me know what you think. (file is zipped, thanks GitHub!)
[fantasyuib.zip](https://github.com/iotech-fvtt/fantasy-ui/files/8219672/fantasyuib.zip)

**Comment by iotech-fvtt** [comment]
Not so much work.. 20 minutes to tweak it just right. I kinda like it, may keep it and merge it with the main repo.

**Comment by Darkiller25** [comment]
I like it too! It looks more in line with the old UI (you should be able to tell me if it's the same values :P )

Thanks! And for those who like it smaller, I think an in-between these two could work. So it's readable, but also not TOO big (I have a 32' monitor so it's not a big deal for me)

**Comment by Darkiller25** [comment]
I always enjoyed the "old school RPG" vibe from the design :)

**Comment by iotech-fvtt** [comment]
How about this
[fantasyuib.zip](https://github.com/iotech-fvtt/fantasy-ui/files/8219765/fantasyuib.zip)
?

**Comment by iotech-fvtt** [comment]
I've also cleaned up some crappy indentation

**Comment by iotech-fvtt** [comment]
A little more cleanup
[fantasyuib.zip](https://github.com/iotech-fvtt/fantasy-ui/files/8219802/fantasyuib.zip)

**Comment by iotech-fvtt** [comment]
If you're happy with the last update I just made, then I am too.. and I'll do build and release so EVERYONE can enjoy this update.

**Comment by iotech-fvtt** [comment]
I couldnt help myself. I went ahead and published the 0.2.1 "Darkiller25" release. Thanks for helping out, I really appreciate it!

**Comment by Darkiller25** [comment]
hahahaha it's an honor! I've been using your UI skin since nearly the beginning of my Foundry discovery!

**Comment by Darkiller25** [comment]
Love the changes so far! Except... this. Otherwise, love the size now! 
![New_UI3](https://user-images.githubusercontent.com/71094682/157590853-a1bc21b7-2ec8-4ab6-b926-5db25c1b80ad.png)

**Comment by iotech-fvtt** [comment]
Actually, I just had that happen to me too, and remembered THAT is why I
made the text so small. And the small text looked awkward, made the button
look huge. I guess since the wrapped text happened to both of us within 2
hours of publishing, maybe I should rethink it. Would you rather:
- Make shorter names for your folders, or;
- Go back to Small text

**Comment by Darkiller25** [comment]
Hmm.... having smaller text was my main issue (not the size of the buttons per se) so I would try to reduce my folder's names for now.

Sorry for the late reply, I went to sleep :P

**Comment by Darkiller25** [comment]
Hey! Did you fix it in the latest version? I don't see the same cutting issue happening anymore! :D

Oh nevermind... when it's a nested folder, it's happening as well :/ 
![New_UI4](https://user-images.githubusercontent.com/71094682/157987346-37f2f9ef-f6ea-4379-afeb-d1f0434a5811.png)

**Comment by iotech-fvtt** [comment]
Tweaked the text fonts a tiny bit smaller

**Comment by iotech-fvtt** [comment]
Sorry to necro this, but I value your feedback. Here is a new build, massive overhaul, even has setting in the module configuration for changing sizes of some things. Let me know what you think? This is FantasyUI 3, be sure to disable FantasyUI 2 before use.

**Comment by iotech-fvtt** [comment]
Latest beta
[fantasy-ui-3.zip](https://github.com/iotech-fvtt/fantasy-ui/files/8310764/fantasy-ui-3.zip)

**Comment by iotech-fvtt** [comment]
Closing this issue; shifting development to FlexUI (at https://github.com/iotech-fvtt/flexui/)
Install manifest: https://raw.githubusercontent.com/iotech-fvtt/flexui/master/module.json

**Comment by iotech-fvtt** [comment]
I took the buttons from 35 pixels tall to 55 pixels, and the text 1.7 times
larger. I could do 45 pixels and 1.3 or 1.4x on the text if you would like?
