### ISSUE TITLE
Feature Request: Themes

### ISSUE THREAD

**Issue by eritzie** [iotech-fvtt/fantasy-ui#15]
Once you get all the kinks worked out and if you are up for a challenge, the one thing I have not seen any of the other UI replacement modules offer is selecting different Themes. For example, if I want a more Fantasy styled UI I would need to choose between this module or the DnD 5E UI. If I want more of a Gothic/Horror styled UI theme I would load the RPG Styled UI. None of the modules offer a one-stop-shop.

**Comment by iotech-fvtt** [comment]
Accepted. Laying the groundwork for  Fantasy/SciFi/Horror. Will take me a bit of time to find art I can use, but I think this is a great idea!

**Comment by iotech-fvtt** [comment]
First beta, three themes. Might need some tweaks.
[fantasy-ui-3.zip](https://github.com/iotech-fvtt/fantasy-ui/files/8310760/fantasy-ui-3.zip)

**Comment by eritzie** [comment]
Cool deal. I will try to check it out tomorrow. The wife and I just got home and I’m going to bed.

**Comment by eritzie** [comment]
Those look good! I ran through all the settings for each theme and did not find any issues. You may want to come up with a more generic name though.

**Comment by iotech-fvtt** [comment]
Agree, been thinking about it.

**Comment by eritzie** [comment]
There is the obvious UI Themes, but that is kind of lame.

**Comment by iotech-fvtt** [comment]
How about FlexUI?

**Comment by iotech-fvtt** [comment]
Closing this issue; shifting development to FlexUI  new repo!!!  (at https://github.com/iotech-fvtt/flexui/)
Install manifest: https://raw.githubusercontent.com/iotech-fvtt/flexui/master/module.json

**Comment by iotech-fvtt** [comment]
I could do that, it'd be pretty easy at this point. I already have a SciFi
UI, although it needs a lot of work.
