### ISSUE TITLE
Suggestion: Add the Ability to Toggle in the Module Settings

### ISSUE THREAD

**Issue by Mrlilal** [iotech-fvtt/fantasy-ui#5]
It would be nice to have a checkbox that can toggle the UI on a per-user basis instead of enabling it for everyone.

**Comment by iotech-fvtt** [comment]
Thanks for the suggestion. That would involve some coding, and realistically, I probably won't do it. Do you know of any other UI mods that do this? I could maybe appropriate some of their code.

**Comment by Mrlilal** [comment]
I understand that it could take some time and completely understand why it would be a pain to implement. I was checking out a few different UI modules, and found one that has something like I suggested.

It's a project called "dnd5edark" and is made by Stryxin. In dnd5edark.js, he implements the checkbox on line 72. His repo can be found here: https://github.com/Stryxin/dnd5edark-foundryvtt

Thanks for the quick reply!

**Comment by iotech-fvtt** [comment]
Hmm, worth checking out. I'll take a peek tomorrow!

**Comment by iotech-fvtt** [comment]
I know you asked this a long time ago, but I finally got around to diving in.,.. and hit a submerged rock. Don't know about when you asked, but the current version of dnd5edark uses Whetstone to tweak the colors and such. I looked into Whetstone integration for another user, and it's just not a direction I want to take FantasyUI. Sorry!

**Comment by iotech-fvtt** [comment]
Your suggestion has been implemented in the next release. Here is a "beta" that will not overwrite current
[fantasy-ui-3.zip](https://github.com/iotech-fvtt/fantasy-ui/files/8310374/fantasy-ui-3.zip)
