### ISSUE TITLE
Suggestion: Whetstone Integration

### ISSUE THREAD

**Issue by akrigline** [iotech-fvtt/fantasy-ui#7]
[Whetstone](https://github.com/MajorVictory/Whetstone) is a UI Theme Manager for FoundryVTT which aims to allow multiple theme overhauls to be installed at once, then individual users can choose which to use. Fantasy-UI would be the perfect use-case.

**Comment by iotech-fvtt** [comment]
I know you made this suggestion forever ago; I took a break from modding for a while. I'm back now and took a look at this suggestion. I'm afraid I just dont care for Whetstone or what it does. The author says it makes it simple for theme authors, but I'd have to disagree. It also looks like if I did add this, then Whetstone would be be required for FantasyUI, and I'm not willing to do that. Sorry :(
