### ISSUE TITLE
Blind Roll background template makes text very unreadable.

### ISSUE THREAD

**Issue by TheAtrivion** [iotech-fvtt/fantasy-ui#8]
The Blind Roll temple and private makes the text almost unreadable.
Either need to lower the transparency or make the text more Bold.
Or maybe an option to change it.
Love the UI, except this new addition XD

**Comment by TheAtrivion** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/67443317/97232639-ca0d1b80-17dd-11eb-955d-9c68ee144382.jpg)
Very difficult to read the finer print in this. =)

**Comment by iotech-fvtt** [comment]
Confirmed, will fix.

**Comment by iotech-fvtt** [comment]
Fixed and released as v0.1.18, thanks for the feedback!
