### ISSUE TITLE
Issue when using Inventory+

### ISSUE THREAD

**Issue by RahzDM** [iotech-fvtt/fantasy-ui#9]
When using Fantasy UI alongside Inventory+ there is a bug. Each inventory section has an arrow to collaps or expand the section. It is there when the sextions are expanded, but when collapsed it disappears and the module must be disabled to see it and expand again.

**Comment by iotech-fvtt** [comment]
I'll look into this as soon as I can, but it may be a few days. I've had a 4TB RAID go bad on me and I am trying to recover all my data, then will have to set up a new Foundry for development.

**Comment by iotech-fvtt** [comment]
Sorry for the long absence! I just tested with Foundry v9, the new current Fantasy UI, and Inventory+ v0.4 - and I dont see what you reported. It seems to be working as intended. Sorry you had troubles, but this seems to be working on Foundry v9
